// client-vue/src/views/Home.vue
<template>
    <div class="flex flex-col justify-center items-center w-11/12 md:w-8/12 xl:w-6/12 mx-auto mt-4 md:mt-8">
        <form @submit.prevent="createItem" class="w-full flex items-center rounded shadow-md py-2 px-3 border-gray-400 border border-solid">
            <input name="name" v-model="name" class="h-12 appearance-none w-full text-gray-700 leading-tight focus:outline-none text-base border-b border-white focus:border-teal-600" placeholder="Add item" autocomplete="off" />
            <button class="ml-4 flex-shrink-0 bg-teal-600 hover:bg-teal-700 border-teal-600 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded" type="button">
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>
            </button>
        </form>

        <div class="items w-full">
            <div v-bind:class="item.done ? 'text-gray-500 line-through' : 'text-gray-800'" class="item w-full flex items-center px-2 py-2 mt-6" v-for="item of items" :key="item.id">
                <input type="checkbox" class="form-checkbox rounded text-teal-600 w-6 h-6 border-2 border-gray-400 cursor-pointer" v-bind:checked="item.done" @change="updateItem(item, {done: status.checked})" />
                <span class="item-name w-full ml-3 text-base select-text outline-none" contenteditable="true" @paste.prevent="onPaste(item, $event)" @keydown="onKeydown(item, $event)" @focusout="updateItem(item, {name: create.textContent})">{{item.name}}</span>

                <button class="item-remove flex-shrink-0 hover:bg-gray-200 rounded-full focus:outline-none p-2 hover:text-black" v-on:click="deleteItem(item)">
                    <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import ApiService from '@/services/api';
import HistoryService from '@/services/history';
import Item from '@/models/item';

export default defineComponent({
    name: 'Home',
    data() {
        const api = new ApiService();
        const history = new HistoryService();
        const items: Array<Item> = [];

        return {
            name: "",
            api,
            history,
            items
        }
    },
    mounted() {
        this.loadItems();
    },
    methods: {
        async loadItems() {
            this.items = await this.api.getItems();
        },

        async submit(e: any) {
            this.createItem(this.name);
        },

        async createItem(name: string, pos?: number) {
            pos = pos || 0;
            let item = new Item().deserialize({name: this.name, pos});
            this.name = "";

            try {
                // Try creating on the server
                item = await this.api.createItem(item)
            } catch (err) {
                // Save creation for later instead
                item = this.history.create(item);
            } finally {
                // Insert new item at pos
                this.items.splice(pos, 0, item);

                // Reset positions
                this.resetPositions();
            }
        },

        async updateItem(item: Item, update: object = {}) {
            Object.assign(item, update);
            item.modified = Date.now();

            try {
                // Try updating on the server
                item = await this.api.updateItem(item);
            } catch (err) {
                // Save the update for later instead
                item = this.history.update(item);
            } finally {
                // Update items array
                for (let i = 0; i < this.items.length; i++) {
                    if (this.items[i].id === item.id) {
                    this.items[i] = item;
                    break;
                    }
                }

                // Reset positions
                this.resetPositions();
            }
        },

        onPaste(item: Item, e: ClipboardEvent) {
            console.log(e);
        },

        onKeydown(item: Item, e: KeyboardEvent) {
            console.log(e);
        },

        async deleteItem(item: Item) {
            item.modified = Date.now();

            try {
                // Try deleting on the server
                await this.api.deleteItem(item);
            } catch (err) {
                // Save deletion for later instead
                item = this.history.delete(item);
                console.log("err", err);
            } finally {
                // Update items array
                for (let i = 0; i < this.items.length; i++) {
                    if (this.items[i].id === item.id) {
                    this.items.splice(i, 1);
                    break;
                    }
                }
            
                // Reset positions
                this.resetPositions();
            }
        },

        /**
         * Set item positions
         * according to their position in the global array
         */
        resetPositions() {
            for (let i = 0; i < this.items.length; i++) {
            this.items[i].pos = i;
            }
        }
    }
});
</script>

// client/src/app/components/home/home.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Title } from '@angular/platform-browser';

import { Item } from '../../models/item.model';

import { ApiService } from '../../services/api.service';
import { HistoryService } from '../../services/history.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit, OnDestroy {
  value: string = '';
  error: string = '';
  items: Array<Item> = [];
  paramSubscription: any;
  params: any = {};
  actionsOpen: boolean = false;
  showConfirmModal: boolean = false;
  modalSuccess: string;
  modalError: string;

  constructor(
    private route: ActivatedRoute,
    public router: Router,
    private titleService: Title,
    private api: ApiService,
    private history: HistoryService
  ) {
    this.titleService.setTitle('Home | To-Do List');
  }

  ngOnInit(): void {
    // Listen for parameter changes
    this.paramSubscription = this.route.queryParams.subscribe(
      async (queryParams) => {
        // Reset error
        this.error = null;

        // Reset items
        this.items = [];

        // Sync history
        await this.history.sync();

        // Load items
        this.loadItems();
      }
    );
  }

  ngOnDestroy() {
    // Remove parameter change subscription
    if (this.paramSubscription) {
      this.paramSubscription.unsubscribe();
    }
  }

  /**
   * Load items
   */
  async loadItems() {
    this.api.getItems(this.params).subscribe({
      next: (items) => {
        this.items = items;
        this.items = this.history.rebuild(this.items);
      },
      error: (err) => {
        console.log('Error fetching items', err);
      },
    });
  }

  /**
   * Create item.
   *
   * @param {string} name
   * @param {number} pos
   */
  async createItem(name: string, pos: number = 0) {
    let item = new Item().deserialize({ name, pos });

    this.api.createItem(item).subscribe({
      next: (createdItem) => {
        // Try creating on the server
        item = createdItem;
      },
      error: (err) => {
        // Save creation for later instead
        item = this.history.create(item);
      },
      complete: () => {
        // Insert new item at pos
        this.items.splice(pos, 0, item);

        // Reset positions
        this.resetPositions();
      },
    });
  }

  /**
   * Update item.
   *
   * @param {Item} item
   * @param {Object} update
   */
  async updateItem(item: Item, update: Object = {}) {
    Object.assign(item, update);
    item.modified = Date.now();

    this.api.updateItem(item).subscribe({
      next: (updatedItem) => {
        // Try updating on the server
        item = updatedItem;
      },
      error: (err) => {
        // Save the update for later instead
        item = this.history.update(item);
      },
      complete: () => {
        // Update items array
        for (let i = 0; i < this.items.length; i++) {
          if (this.items[i].id === item.id) {
            this.items[i] = item;
            break;
          }
        }

        // Reset positions
        this.resetPositions();
      },
    });
  }

  /**
   * Delete all checked items.
   *
   * @param {boolean} confirmed
   */
  deleteDone(confirmed: boolean = false): void {
    const doneItems = this.items.filter((item) => item.done);

    // Check if there are items to be deleted
    if (doneItems.length == 0) {
      return;
    }

    if (!confirmed) {
      // Show confirmation dialog
      this.showConfirmModal = true;
      return;
    }

    // Close dropdown
    this.actionsOpen = false;

    // Delete items
    doneItems.forEach((item) => {
      this.deleteItem(item);
    });
  }

  /**
   * Delete item.
   *
   * @param {Item} item
   */
  async deleteItem(item: Item) {
    item.modified = Date.now();

    // Try deleting on the server
    this.api.deleteItem(item).subscribe({
      error: (err) => {
        // Save deletion for later instead
        item = this.history.delete(item);
        console.log('err', err);
      },
      complete: () => {
        // Update items array
        for (let i = 0; i < this.items.length; i++) {
          if (this.items[i].id === item.id) {
            this.items.splice(i, 1);
            break;
          }
        }

        // Reset positions
        this.resetPositions();
      },
    });
  }

  /**
   * Catch paste event.
   *
   * @param {Item} item
   * @param {event} event
   */
  async onPaste(item: Item, event: ClipboardEvent) {
    const target = <HTMLElement>event.target;

    // Get index of current item
    let index = item.pos + 1;

    // Get caret position
    const caretPos = this.getCaretPosition(target);

    // Get text left of caret
    const leftOfCaret = target.innerText.substring(0, caretPos);

    // Get text right of caret
    const rightOfCaret = target.innerText.substring(caretPos);

    // Get pasted text
    const clipboardData = event.clipboardData || window['clipboardData'];
    const fullText = leftOfCaret + clipboardData.getData('text') + rightOfCaret;
    const lines = fullText.split('\n');

    for (let i = 0; i < lines.length; i++) {
      if (i === 0) {
        // Update current item
        await this.updateItem(item, { name: lines[i], pos: index - 1 });
      } else {
        await this.createItem(lines[i], index);
      }

      index++;
    }
  }

  /**
   * Intercept keydown.
   *
   * @param {Item} item
   * @param {KeyboardEvent} event
   */
  async onKeydown(item: Item, event: KeyboardEvent) {
    if (event.which !== 13) {
      return;
    }

    event.preventDefault();

    const target = <HTMLElement>event.target;

    // Get index of current item
    const index = item.pos + 1;

    // Get caret position
    const caretPos = this.getCaretPosition(target);

    // Determine name of current item
    const currentName = target.innerText.substring(0, caretPos).trim();

    // Determine name of new item
    const newName = target.innerText.substring(caretPos);

    // Update current item
    await this.updateItem(item, { name: currentName, pos: index - 1 });

    // Create new item
    await this.createItem(newName, index);

    // Focus on new item
    setTimeout(() => {
      (<HTMLElement>(
        document.querySelector(
          '.item:nth-child(' + (index + 1) + ') [contenteditable]'
        )
      )).focus();
    }, 10);
  }

  /**
   * Set item positions
   * according to their position in the global array
   */
  resetPositions() {
    for (let i = 0; i < this.items.length; i++) {
      this.items[i].pos = i;
    }
  }

  /**
   * Get caret position within editable HTML.
   *
   * @param {HTMLElement} elem
   * @returns {number}
   */
  getCaretPosition(elem: HTMLElement) {
    if (window.getSelection) {
      const sel = window.getSelection();

      if (sel.rangeCount) {
        let range = sel.getRangeAt(0);
        if (range.commonAncestorContainer.parentNode == elem) {
          return range.endOffset;
        }
      }
    } else if (document['selection'] && document['selection'].createRange) {
      const range = document['selection'].createRange();

      if (range.parentElement() == elem) {
        const tempEl = document.createElement('span');
        elem.insertBefore(tempEl, elem.firstChild);

        const tempRange = range.duplicate();
        tempRange.moveToElementText(tempEl);
        tempRange.setEndPoint('EndToEnd', range);

        return tempRange.text.length;
      }
    }

    return 0;
  }
}

<div
  class="flex flex-col justify-center items-center w-11/12 md:w-8/12 xl:w-6/12 mx-auto mt-4 md:mt-8"
>
  <!-- Add item -->
  <form
    #create="ngForm"
    (ngSubmit)="createItem(create.value.name); create.reset()"
    class="w-full flex items-center rounded shadow-md py-2 px-3 border-gray-300 border border-solid"
  >
    <div class="input-container" style="width: 100%">
      <input
        style="border: none; width: 100%"
        name="name"
        type="text"
        ngModel
        #name
        placeholder="Add item"
        autocomplete="off"
      />
      <span class="focus-border"></span>
    </div>

    <!-- Plus button -->
    <button
      class="ml-4 flex-shrink-0 bg-teal-600 hover:bg-teal-700 border-teal-600 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded"
      type="submit"
    >
      <svg
        class="h-6 w-6"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M12 6v6m0 0v6m0-6h6m-6 0H6"
        />
      </svg>
    </button>

    <!-- Action menu -->
    <div class="dropdown">
      <!-- Action menu button -->
      <button
        class="focus:outline-none block ml-4 flex-shrink-0 hover:bg-teal-700 hover:text-white text-sm text-gray-500 py-1 px-1 rounded"
        type="button"
        (click)="actionsOpen = !actionsOpen"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-6 w-6"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"
          />
        </svg>
      </button>

      <!-- Action menu dropdown -->
      <div *ngIf="actionsOpen" class="dropdown-menu">
        <!-- Backdrop -->
        <button
          tabindex="-1"
          class="dropdown-backdrop"
          (click)="actionsOpen = false"
        ></button>

        <!-- Dropdown menu -->
        <div class="dropdown-content">
          <div
            class="dropdown-item"
            (click)="actionsOpen = false; deleteDone()"
          >
            Remove checked
          </div>
        </div>
      </div>
    </div>
  </form>

  <!-- Items -->
  <div class="items w-full">
    <!-- Undone items -->
    <div
      class="item w-full flex items-center px-2 py-2 mt-6 text-gray-800"
      *ngFor="let item of items | undone"
    >
      <input
        type="checkbox"
        class="checkbox"
        #status
        [checked]="item.done"
        (change)="updateItem(item, { done: status.checked })"
      />
      <span
        #create
        class="item-name w-full ml-3 text-base select-text outline-none"
        contenteditable="true"
        (paste)="onPaste(item, $event)"
        (keydown)="onKeydown(item, $event)"
        (focusout)="updateItem(item, { name: create.textContent })"
        >{{ item.name }}</span
      >

      <button
        class="item-remove flex-shrink-0 hover:bg-gray-200 rounded-full focus:outline-none p-2 hover:text-black"
        (click)="deleteItem(item)"
      >
        <svg
          class="fill-current w-4 h-4"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </button>
    </div>

    <!-- Done items -->
    <div
      class="item w-full flex items-center px-2 py-2 mt-6 text-gray-500 line-through"
      *ngFor="let item of items | done"
    >
      <input
        type="checkbox"
        class="checkbox"
        #status
        [checked]="item.done"
        (change)="updateItem(item, { done: status.checked })"
      />
      <span
        #create
        class="item-name w-full ml-3 text-base select-text outline-none"
        contenteditable="true"
        (paste)="onPaste(item, $event)"
        (keydown)="onKeydown(item, $event)"
        (focusout)="updateItem(item, { name: create.textContent })"
        >{{ item.name }}</span
      >

      <button
        class="item-remove flex-shrink-0 hover:bg-gray-200 rounded-full focus:outline-none p-2 hover:text-black"
        (click)="deleteItem(item)"
      >
        <svg
          class="fill-current w-4 h-4"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </button>
    </div>
  </div>

  <app-dialog
    [(show)]="showConfirmModal"
    [actionName]="'OK'"
    [title]="'Delete?'"
    (action)="deleteDone(true)"
    [autoHide]="true"
  ></app-dialog>
</div>
