// client-vue/src/views/AccessManagement.vue
<template>
    <div class="flex flex-col w-11/12 md:w-8/12 xl:w-6/12 mx-auto mt-4 md:mt-8">
        <h1 class="text-5xl text-gray-800">Access Management</h1>

        <!-- Service tokens -->
        <h2 class="text-3xl mt-4">Service tokens</h2>

        <div class="items w-full">
            <div class="w-full flex items-center px-2 py-2 mt-4" v-for="token of tokens" :key="token.id">
                <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" /></svg>
                <span class="w-full ml-3 text-base outline-none">
                    {{token.name}}
                    
                </span>

                <span class="ml-auto text-gray-500 whitespace-no-wrap">({{util.timestampToDate(token.created)}})</span>

                <button class="ml-3 flex-shrink-0 hover:bg-gray-200 rounded-full focus:outline-none p-2 hover:text-black" @click="deleteToken(token)">
                    <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                </button>
            </div>
        </div>

        <!-- Create service token -->
        <button class="mt-4 w-48 bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button" @click="showModal = true">
            Create Service Token
        </button>

        <CustomDialog v-model:show="showModal" :actionName="modalActionName" title="Create Service Token" :error="modalError" :success="modalSuccess" :fields="modalFields" v-on:action="createToken($event.name)" />
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import CustomDialog from '@/components/CustomDialog.vue';
import ApiService from '@/services/api';
import ServiceToken from '@/models/service-token';

export default defineComponent({
    name: 'access-management',
    components: {
        CustomDialog,
    },
    data() {
        const tokens: Array<ServiceToken> = [];
        const api = new ApiService();

        return {
            api,
            tokens,
            showModal: false,
            modalActionName: "Click",
            modalError: "",
            modalSuccess: "",
            modalFields: ['name']
        }
    },
    methods: {
        async createToken(name: string) {
            try {
                const token = await this.api.createServiceToken(name);
                this.modalSuccess = token.token!;

                this.loadTokens();
            } catch (err) {
                console.log("Error creating token", err);
                this.modalError = err;
            }
        },

        async loadTokens() {
            try {
                this.tokens = await this.api.loadServiceTokens();
            } catch (err) {
                console.log("Error loading tokens", err);
            }
        },

        async deleteToken(token: ServiceToken) {
            try {
                await this.api.deleteServiceToken(token.id!);

                this.loadTokens();
            } catch (err) {
                console.log("Error deleting token", err);
            }
        }
    }
});
</script>

// client/src/app/components/access-management/access-management.component.ts
import { Component, HostListener } from '@angular/core';
import { Title } from '@angular/platform-browser';

import { ServiceToken } from '../../models/service-token.model';
import { ApiService } from '../../services/api.service';
import { UtilService } from '../../services/util.service';

@Component({
  selector: 'app-access-management',
  templateUrl: './access-management.component.html',
  styleUrls: ['./access-management.component.scss'],
})
export class AccessManagementComponent {
  tokens: Array<ServiceToken> = [];

  showModal: boolean = false;

  modalTitle: string = 'Create Service Token';

  modalActionName: string = 'Create';

  modalFields: Array<string> = ['name'];

  modalSuccess: string = '';

  modalError: string = '';

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if (event.code === 'Escape' || event.code === 'Esc') {
      this.showModal = false;
    }
  }

  constructor(
    private titleService: Title,
    private api: ApiService,
    private util: UtilService
  ) {
    this.titleService.setTitle('Access Management | To-Do List');

    // Load service tokens
    this.loadTokens();
  }

  async createToken(name: string) {
    this.api.createServiceToken(name).subscribe({
      next: (token) => {
        this.modalSuccess = <string>token.token;

        this.loadTokens();
      },
      error: (err) => {
        console.error('Error creating token', err);
        this.modalError = <string>err;
      },
    });
  }

  async loadTokens() {
    this.api.loadServiceTokens().subscribe({
      next: (tokens) => {
        this.tokens = tokens;
      },
      error: (err) => {
        console.error('Error loading tokens', err);
      },
    });
  }

  async deleteToken(token: ServiceToken) {
    this.api.deleteServiceToken(token.id).subscribe({
      complete: () => {
        this.loadTokens();
      },
      error: (err) => {
        console.error('Error deleting token', err);
      },
    });
  }
}

<div class="page-wrapper col-xl-8">
  <h1 class="page-title">Access Management</h1>

  <!-- Service tokens -->
  <h2>Service tokens</h2>

  <div class="items w-full">
    <div
      class="w-full flex items-center px-2 py-2 mt-4"
      *ngFor="let token of tokens"
    >
      <svg
        class="fill-current w-4 h-4"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"
        />
      </svg>
      <span class="w-full ml-3 text-base outline-none">
        {{ token.name }}
      </span>

      <span class="ml-auto text-gray-500 whitespace-no-wrap"
        >({{ util.timestampToDate(token.created) }})</span
      >

      <button
        class="ml-3 flex-shrink-0 hover:bg-gray-200 rounded-full focus:outline-none p-2 hover:text-black"
        (click)="deleteToken(token)"
      >
        <svg
          class="fill-current w-4 h-4"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
          />
        </svg>
      </button>
    </div>
  </div>

  <!-- Create service token -->
  <button
    class="mt-4 w-48 bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
    type="button"
    (click)="showModal = true"
  >
    Create Service Token
  </button>

  <app-dialog
    [(show)]="showModal"
    [actionName]="modalActionName"
    [title]="modalTitle"
    [error]="modalError"
    [success]="modalSuccess"
    [fields]="modalFields"
    (action)="createToken($event.name)"
  ></app-dialog>
</div>
